version: "3"

services:
    app:
        container_name: santa_secet_app
        build: .
        restart: always
        ports:
            - "8700:8000" #pc:container
        volumes:
            - .:/var/www
        networks:
            - bridge_connection

    db:
        container_name: santa_secet_mysql
        image: mysql:5.7
        restart: always
        ports:
            - "5606:3306"
        environment:
            - MYSQL_DATABASE=secret_santa
            - MYSQL_ROOT_PASSWORD=123
        volumes:
            - ./.docker/mysql/db_data:/var/lib/mysql
        networks:
            - bridge_connection

networks:
    bridge_connection:
        driver: bridge

volumes:
    db_data: